name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Railway Deployment via Webhook
        run: |
          curl -X POST "${{ secrets.RAILWAY_DEPLOYMENT_WEBHOOK }}"
