name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f 'uvicorn main:app' || true
            sudo systemctl restart fastapi.service
            python3 -m uvicorn main:app --host 0.0.0.0 --port 8000